# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: TimescaleDB
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: TimescaleDB
    # <string, required> datasource type. Required
    type: postgres
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
    uid: timescaledb
    # <string> url
    url: timescaledb:5432
    # <string> database user, if used
    user: postgres
    # <string> database name, if used
    database: postgres
    # <bool> enable/disable basic auth
    basicAuth: false
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    # <map> fields that will be converted to json and stored in jsonData
    jsonData:
      postgresVersion: 1000
      sslmode: disable
      timeInterval: "1s"
      timescaledb: true
    # <string> json object of data that will be encrypted.
    secureJsonData:
      # <string> database password, if used
      password: password

    # <bool> allow users to edit datasources from the UI.
    editable: false
    readOnly: true
    version: 1
